Repository obsei/obsei, pull requests merged in 2021-09, with the labels that each got.

#190 Bug fix: Fix Twitter Source Config import issue
  README.md
  example/jira_example.py
  obsei/source/email_source.py
  obsei/source/playstore_reviews.py
  obsei/source/reddit_scrapper.py
  obsei/source/twitter_source.py
  sample-ui/config.yaml
Labels: bug, breaking changes

#191 add text classification analyzer
  obsei/analyzer/classification_analyzer.py
  test/conftest.py
  test/test_analyzer.py
Labels: analyzer

#193 Bug: Fixing import issues along
  README.md
  obsei/__init__.py
  obsei/analyzer/__init__.py
  obsei/analyzer/base_analyzer.py
  obsei/configuration.py
  obsei/postprocessor/__init__.py
  obsei/postprocessor/base_postprocessor.py
  obsei/preprocessor/__init__.py
  obsei/preprocessor/base_preprocessor.py
  obsei/sink/__init__.py
  obsei/sink/base_sink.py
  obsei/sink/elasticsearch_sink.py
  obsei/sink/jira_sink.py
  obsei/sink/slack_sink.py
  obsei/sink/zendesk_sink.py
  obsei/source/__init__.py
  obsei/source/base_source.py
  obsei/source/email_source.py
  obsei/source/facebook_source.py
  obsei/source/playstore_reviews.py
  obsei/source/reddit_source.py
  obsei/source/twitter_source.py
  obsei/workflow/base_store.py
  test/test_imports.py
Labels: bug
